<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/affiliates.php');
	include_once(__DIR__ . '/affiliates_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('affiliates');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'affiliates';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`affiliates`.`id`" => "id",
		"`affiliates`.`total_affiliate_bonus`" => "total_affiliate_bonus",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`affiliates`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`affiliates`.`id`" => "id",
		"`affiliates`.`total_affiliate_bonus`" => "total_affiliate_bonus",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`affiliates`.`id`" => "ID",
		"`affiliates`.`total_affiliate_bonus`" => "Total affiliate bonus",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`affiliates`.`id`" => "id",
		"`affiliates`.`total_affiliate_bonus`" => "total_affiliate_bonus",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`affiliates` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'affiliates_view.php';
	$x->TableTitle = 'Affiliates';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`affiliates`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Total affiliate bonus', ];
	$x->ColFieldName = ['total_affiliate_bonus', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/affiliates_templateTV.html';
	$x->SelectedTemplate = 'templates/affiliates_templateTVS.html';
	$x->TemplateDV = 'templates/affiliates_templateDV.html';
	$x->TemplateDVP = 'templates/affiliates_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: affiliates_init
	$render = true;
	if(function_exists('affiliates_init')) {
		$args = [];
		$render = affiliates_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: affiliates_header
	$headerCode = '';
	if(function_exists('affiliates_header')) {
		$args = [];
		$headerCode = affiliates_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: affiliates_footer
	$footerCode = '';
	if(function_exists('affiliates_footer')) {
		$args = [];
		$footerCode = affiliates_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
