<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/companies.php');
	include_once(__DIR__ . '/companies_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('companies');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'companies';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`companies`.`id`" => "id",
		"`companies`.`image`" => "image",
		"`companies`.`name`" => "name",
		"`companies`.`share_price`" => "share_price",
		"`companies`.`percentage`" => "percentage",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`companies`.`id`',
		2 => 2,
		3 => 3,
		4 => '`companies`.`share_price`',
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`companies`.`id`" => "id",
		"`companies`.`image`" => "image",
		"`companies`.`name`" => "name",
		"`companies`.`share_price`" => "share_price",
		"`companies`.`percentage`" => "percentage",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`companies`.`id`" => "ID",
		"`companies`.`name`" => "Name",
		"`companies`.`share_price`" => "Share price",
		"`companies`.`percentage`" => "Percentage",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`companies`.`id`" => "id",
		"`companies`.`name`" => "name",
		"`companies`.`share_price`" => "share_price",
		"`companies`.`percentage`" => "percentage",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`companies` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'companies_view.php';
	$x->TableTitle = 'Companies';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`companies`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 80, 150, ];
	$x->ColCaption = ['ID', 'Image', 'Name', 'Share price', 'Percentage', ];
	$x->ColFieldName = ['id', 'image', 'name', 'share_price', 'percentage', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/companies_templateTV.html';
	$x->SelectedTemplate = 'templates/companies_templateTVS.html';
	$x->TemplateDV = 'templates/companies_templateDV.html';
	$x->TemplateDVP = 'templates/companies_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: companies_init
	$render = true;
	if(function_exists('companies_init')) {
		$args = [];
		$render = companies_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: companies_header
	$headerCode = '';
	if(function_exists('companies_header')) {
		$args = [];
		$headerCode = companies_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: companies_footer
	$footerCode = '';
	if(function_exists('companies_footer')) {
		$args = [];
		$footerCode = companies_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
