<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/investments.php');
	include_once(__DIR__ . '/investments_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('investments');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'investments';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`investments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"IF(    CHAR_LENGTH(`companies1`.`name`), CONCAT_WS('',   `companies1`.`name`), '') /* Company */" => "company",
		"`investments`.`amount`" => "amount",
		"`investments`.`pay_per_day`" => "pay_per_day",
		"if(`investments`.`date_invested`,date_format(`investments`.`date_invested`,'%d/%m/%Y %H:%i'),'')" => "date_invested",
		"`investments`.`shares_sold`" => "shares_sold",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`investments`.`id`',
		2 => '`users1`.`username`',
		3 => '`companies1`.`name`',
		4 => 4,
		5 => 5,
		6 => '`investments`.`date_invested`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`investments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"IF(    CHAR_LENGTH(`companies1`.`name`), CONCAT_WS('',   `companies1`.`name`), '') /* Company */" => "company",
		"`investments`.`amount`" => "amount",
		"`investments`.`pay_per_day`" => "pay_per_day",
		"if(`investments`.`date_invested`,date_format(`investments`.`date_invested`,'%d/%m/%Y %H:%i'),'')" => "date_invested",
		"`investments`.`shares_sold`" => "shares_sold",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`investments`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "User id",
		"IF(    CHAR_LENGTH(`companies1`.`name`), CONCAT_WS('',   `companies1`.`name`), '') /* Company */" => "Company",
		"`investments`.`amount`" => "Amount",
		"`investments`.`pay_per_day`" => "Pay per day",
		"`investments`.`date_invested`" => "Date invested",
		"`investments`.`shares_sold`" => "Shares sold",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`investments`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"IF(    CHAR_LENGTH(`companies1`.`name`), CONCAT_WS('',   `companies1`.`name`), '') /* Company */" => "company",
		"`investments`.`amount`" => "amount",
		"`investments`.`pay_per_day`" => "pay_per_day",
		"if(`investments`.`date_invested`,date_format(`investments`.`date_invested`,'%d/%m/%Y %H:%i'),'')" => "date_invested",
		"`investments`.`shares_sold`" => "shares_sold",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['user_id' => 'User id', 'company' => 'Company', ];

	$x->QueryFrom = "`investments` LEFT JOIN `users` as users1 ON `users1`.`id`=`investments`.`user_id` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`investments`.`company` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'investments_view.php';
	$x->TableTitle = 'Investments';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`investments`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['User id', 'Company', 'Amount', 'Pay per day', 'Date invested', 'Shares sold', ];
	$x->ColFieldName = ['user_id', 'company', 'amount', 'pay_per_day', 'date_invested', 'shares_sold', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/investments_templateTV.html';
	$x->SelectedTemplate = 'templates/investments_templateTVS.html';
	$x->TemplateDV = 'templates/investments_templateDV.html';
	$x->TemplateDVP = 'templates/investments_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: investments_init
	$render = true;
	if(function_exists('investments_init')) {
		$args = [];
		$render = investments_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: investments_header
	$headerCode = '';
	if(function_exists('investments_header')) {
		$args = [];
		$headerCode = investments_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: investments_footer
	$footerCode = '';
	if(function_exists('investments_footer')) {
		$args = [];
		$footerCode = investments_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
