<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/users.php');
	include_once(__DIR__ . '/users_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('users');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'users';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`users`.`id`" => "id",
		"`users`.`first_name`" => "first_name",
		"`users`.`last_name`" => "last_name",
		"`users`.`id_number`" => "id_number",
		"`users`.`username`" => "username",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"if(`users`.`date_joined`,date_format(`users`.`date_joined`,'%d/%m/%Y %H:%i'),'')" => "date_joined",
		"`users`.`refferal_code`" => "refferal_code",
		"`users`.`reffered_by`" => "reffered_by",
		"`users`.`ref_paid`" => "ref_paid",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`users`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`users`.`date_joined`',
		9 => 9,
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`users`.`id`" => "id",
		"`users`.`first_name`" => "first_name",
		"`users`.`last_name`" => "last_name",
		"`users`.`id_number`" => "id_number",
		"`users`.`username`" => "username",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"if(`users`.`date_joined`,date_format(`users`.`date_joined`,'%d/%m/%Y %H:%i'),'')" => "date_joined",
		"`users`.`refferal_code`" => "refferal_code",
		"`users`.`reffered_by`" => "reffered_by",
		"`users`.`ref_paid`" => "ref_paid",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`users`.`id`" => "ID",
		"`users`.`first_name`" => "First name",
		"`users`.`last_name`" => "Last name",
		"`users`.`id_number`" => "Id number",
		"`users`.`username`" => "Username",
		"`users`.`email`" => "Email",
		"`users`.`password`" => "Password",
		"`users`.`date_joined`" => "Joining date",
		"`users`.`refferal_code`" => "Refferal code",
		"`users`.`reffered_by`" => "Reffered by",
		"`users`.`ref_paid`" => "Ref paid",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`users`.`id`" => "id",
		"`users`.`first_name`" => "first_name",
		"`users`.`last_name`" => "last_name",
		"`users`.`id_number`" => "id_number",
		"`users`.`username`" => "username",
		"`users`.`email`" => "email",
		"`users`.`password`" => "password",
		"if(`users`.`date_joined`,date_format(`users`.`date_joined`,'%d/%m/%Y %H:%i'),'')" => "date_joined",
		"`users`.`refferal_code`" => "refferal_code",
		"`users`.`reffered_by`" => "reffered_by",
		"`users`.`ref_paid`" => "ref_paid",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`users` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'users_view.php';
	$x->TableTitle = 'Users';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`users`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['First name', 'Last name', 'Id number', 'Username', 'Email', 'Password', 'Joining date', 'Refferal code', 'Reffered by', 'Ref paid', ];
	$x->ColFieldName = ['first_name', 'last_name', 'id_number', 'username', 'email', 'password', 'date_joined', 'refferal_code', 'reffered_by', 'ref_paid', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/users_templateTV.html';
	$x->SelectedTemplate = 'templates/users_templateTVS.html';
	$x->TemplateDV = 'templates/users_templateDV.html';
	$x->TemplateDVP = 'templates/users_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: users_init
	$render = true;
	if(function_exists('users_init')) {
		$args = [];
		$render = users_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: users_header
	$headerCode = '';
	if(function_exists('users_header')) {
		$args = [];
		$headerCode = users_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: users_footer
	$footerCode = '';
	if(function_exists('users_footer')) {
		$args = [];
		$footerCode = users_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
