<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/wallets.php');
	include_once(__DIR__ . '/wallets_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('wallets');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'wallets';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`wallets`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"`wallets`.`wallet_type`" => "wallet_type",
		"`wallets`.`available_amount`" => "available_amount",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`wallets`.`id`',
		2 => '`users1`.`username`',
		3 => 3,
		4 => '`wallets`.`available_amount`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`wallets`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"`wallets`.`wallet_type`" => "wallet_type",
		"`wallets`.`available_amount`" => "available_amount",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`wallets`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "User id",
		"`wallets`.`wallet_type`" => "Wallet type",
		"`wallets`.`available_amount`" => "Available amount",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`wallets`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* User id */" => "user_id",
		"`wallets`.`wallet_type`" => "wallet_type",
		"`wallets`.`available_amount`" => "available_amount",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['user_id' => 'User id', ];

	$x->QueryFrom = "`wallets` LEFT JOIN `users` as users1 ON `users1`.`id`=`wallets`.`user_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'wallets_view.php';
	$x->TableTitle = 'Wallets';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`wallets`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['User id', 'Wallet type', 'Available amount', ];
	$x->ColFieldName = ['user_id', 'wallet_type', 'available_amount', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/wallets_templateTV.html';
	$x->SelectedTemplate = 'templates/wallets_templateTVS.html';
	$x->TemplateDV = 'templates/wallets_templateDV.html';
	$x->TemplateDVP = 'templates/wallets_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: wallets_init
	$render = true;
	if(function_exists('wallets_init')) {
		$args = [];
		$render = wallets_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: wallets_header
	$headerCode = '';
	if(function_exists('wallets_header')) {
		$args = [];
		$headerCode = wallets_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: wallets_footer
	$footerCode = '';
	if(function_exists('wallets_footer')) {
		$args = [];
		$footerCode = wallets_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
