<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/withdrawals.php');
	include_once(__DIR__ . '/withdrawals_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('withdrawals');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'withdrawals';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`withdrawals`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* Username */" => "user_id",
		"`withdrawals`.`amount`" => "amount",
		"`withdrawals`.`phone_number`" => "phone_number",
		"if(`withdrawals`.`date`,date_format(`withdrawals`.`date`,'%d/%m/%Y'),'')" => "date",
		"`withdrawals`.`status`" => "status",
		"`withdrawals`.`mpesa_code`" => "mpesa_code",
		"`withdrawals`.`payment_refference`" => "payment_refference",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`withdrawals`.`id`',
		2 => '`users1`.`username`',
		3 => 3,
		4 => 4,
		5 => '`withdrawals`.`date`',
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`withdrawals`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* Username */" => "user_id",
		"`withdrawals`.`amount`" => "amount",
		"`withdrawals`.`phone_number`" => "phone_number",
		"if(`withdrawals`.`date`,date_format(`withdrawals`.`date`,'%d/%m/%Y'),'')" => "date",
		"`withdrawals`.`status`" => "status",
		"`withdrawals`.`mpesa_code`" => "mpesa_code",
		"`withdrawals`.`payment_refference`" => "payment_refference",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`withdrawals`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* Username */" => "Username",
		"`withdrawals`.`amount`" => "Amount",
		"`withdrawals`.`phone_number`" => "Phone number",
		"`withdrawals`.`date`" => "Date",
		"`withdrawals`.`status`" => "Status",
		"`withdrawals`.`mpesa_code`" => "Mpesa code",
		"`withdrawals`.`payment_refference`" => "Payment refference",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`withdrawals`.`id`" => "id",
		"IF(    CHAR_LENGTH(`users1`.`username`), CONCAT_WS('',   `users1`.`username`), '') /* Username */" => "user_id",
		"`withdrawals`.`amount`" => "amount",
		"`withdrawals`.`phone_number`" => "phone_number",
		"if(`withdrawals`.`date`,date_format(`withdrawals`.`date`,'%d/%m/%Y'),'')" => "date",
		"`withdrawals`.`status`" => "status",
		"`withdrawals`.`mpesa_code`" => "mpesa_code",
		"`withdrawals`.`payment_refference`" => "payment_refference",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['user_id' => 'Username', ];

	$x->QueryFrom = "`withdrawals` LEFT JOIN `users` as users1 ON `users1`.`id`=`withdrawals`.`user_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'withdrawals_view.php';
	$x->TableTitle = 'Withdrawals';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`withdrawals`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Username', 'Amount', 'Phone number', 'Date', 'Status', 'Mpesa code', 'Payment refference', ];
	$x->ColFieldName = ['user_id', 'amount', 'phone_number', 'date', 'status', 'mpesa_code', 'payment_refference', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/withdrawals_templateTV.html';
	$x->SelectedTemplate = 'templates/withdrawals_templateTVS.html';
	$x->TemplateDV = 'templates/withdrawals_templateDV.html';
	$x->TemplateDVP = 'templates/withdrawals_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: withdrawals_init
	$render = true;
	if(function_exists('withdrawals_init')) {
		$args = [];
		$render = withdrawals_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: withdrawals_header
	$headerCode = '';
	if(function_exists('withdrawals_header')) {
		$args = [];
		$headerCode = withdrawals_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: withdrawals_footer
	$footerCode = '';
	if(function_exists('withdrawals_footer')) {
		$args = [];
		$footerCode = withdrawals_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
